default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3305
  socket: /var/run/mysqld/mysqld.sock
  database: reimplementation_development
  username: root
  password: password


development:
  <<: *default
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_development?') %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_test?') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_production?') %>